### ISSUE TITLE
Краш на Линуксе (Manjaro)

### ISSUE THREAD

**Issue by Duck375** [klen-list/gmod-bombass-issues#2]
![image](https://user-images.githubusercontent.com/58744956/148245845-6ab56a09-e2ad-4bde-ae52-4bab6f23047d.png)
Ветка: x86-64 - Chromium + 64-bit binaries
Запускал обычную (нативную) версию, не через Proton
Краш происходит после полной загрузки, но до начала отрисовки графики, заходил дважды, оба - краш (Все еще видно экран загрузки на прогрессе написано "Ready to Play", но и Мотд уже открылся и загрузился). Дамп в виде txt прикреплю ниже
На других серверах все работает стабильно
1 заход:
[efa1a73e-aeaa-4945-085f89b7-ae2023d9.txt](https://github.com/klen-list/gmod-bombass-issues/files/7816016/efa1a73e-aeaa-4945-085f89b7-ae2023d9.txt)
 
2 заход:
[7ee3becc-498c-454c-721f168e-615f678d.txt](https://github.com/klen-list/gmod-bombass-issues/files/7816019/7ee3becc-498c-454c-721f168e-615f678d.txt)
 
 Оба дампа в архиве (гит не поддерживает их формат)
[dumps.zip](https://github.com/klen-list/gmod-bombass-issues/files/7816046/dumps.zip)

**Comment by klen-list** [comment]
![firefox_R06IXVDq9R](https://user-images.githubusercontent.com/49125075/148285421-4a0e280e-9d1c-4dd2-a2ab-e92408c2bc7c.png)
![firefox_xo27gRdPDz](https://user-images.githubusercontent.com/49125075/148285425-bb9e484e-76ab-45c3-912c-a8a3a5b35ee5.png)
Оба краша происходят на одной и той же точке, стактрейса луа нет, так что проблему можно решить только обращением с дампами к рубату.

**Comment by Duck375** [comment]
Ок отправил проблему на гит гмода
